# Generated by Django 3.1.2 on 2021-05-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images/'),
        ),
    ]
